### ISSUE TITLE
[Broken] Code Generator - Unhandled Exception: SystemArgumentOutOfRangeException: StartIndex cannot be less than zero. Parameter name: startIndex

### ISSUE THREAD

**Issue by vavavr00m** [andreashagstrom/SpawnCodeGenerator#3]
[Output.txt](https://github.com/andreashagstrom/SpawnCodeGenerator/files/11686206/Output.txt)

No item spawncodes were generated and throws an error:

![image](https://github.com/andreashagstrom/SpawnCodeGenerator/assets/4675132/ff29408a-6fab-4b13-80bf-1133b3a88430)

**Comment by andreashagstrom** [comment]
As I already replied to you on the correct thread. This code is not designed to fetch the vanilla names nor to be placed to get all different mods in one go. Please continue the discussion on that thread.
